services:

  redis:
    image: redis:7-alpine
    container_name: reservar_cancha_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  api:
    build: .
    container_name: reservar_cancha_api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    restart: unless-stopped
